name: eRecht24 NPM Package

on: [push]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  ERECHT24_PLUGIN_KEY: ${{ secrets.ERECHT24_PLUGIN_KEY }}

jobs:
  eRecht24:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: npm ci

      - name: Dependencies audit
        run: npm audit --audit-level=high

      - name: Build
        run: npm run build

      - name: Format check
        run: npm run format:check

      - name: Lint check
        run: npm run lint:check

      - name: Spell check
        run: npm run spell:check

      - name: Test
        run: yarn run test --outputFile sonar-report.xml --reporter vitest-sonar-reporter

      - name: Coverage
        run: npm run test:coverage

      - name: Connect to Tailscale Network for Sonarqube
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Sonarqube scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
